export default {
    countrys: [
        { name: 'Australia'},
        { name: 'Austria'},
        { name: 'Belgium'},
        { name: 'Canada'},
        { name: 'Denmark'},
        { name: 'Estonia'},
        { name: 'Finland'},
        { name: 'France'},
        { name: 'Germany'},
        { name: 'Greece'},
        { name: 'Hong Kong SAR China'},
        { name: 'Ireland'},
        { name: 'Italy'},
        { name: 'Japan'},
        { name: 'Latvia'},
        { name: 'Lithuania'},
        { name: 'Luxembourg'},
        { name: 'Netherlands'},
        { name: 'New Zealand'},
        { name: 'Norway'},
        { name: 'Poland'},
        { name: 'Portugal'},
        { name: 'Singapore'},
        { name: 'Slovakia'},
        { name: 'Slovenia'},
        { name: 'Spain'},
        { name: 'Sweden'},
        { name: 'Switzerland'},
        { name: 'United Kingdom'},
        { name: 'United States'},
    ],
    countrys_alph:[],
    initialize() {
        this.countrys_alph = _.sortBy(this.countrys, ['name'])
    },
}
